src/Entity/AboutUs.php
<?php

namespace App\Entity;

use App\Repository\AboutUsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AboutUsRepository::class)
 */
class AboutUs
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $job;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getJob(): ?string
    {
        return $this->job;
    }

    public function setJob(string $job): self
    {
        $this->job = $job;

        return $this;
    }
}

templates/aboutus/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Qui sommes nous ?{% endblock %}

{% block body %}
<!-- Header -->
<div class="bg-success text-center py-5 mb-4" style="margin: 15px 0px;">
    <div class="container">
      <h1 class="font-weight-light text-white">Rencontrez l'équipe</h1>
    </div>
  </div>
  
  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <!-- Team Member 1 -->
      {% for aboutus in aboutuss %}
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-0 shadow">
          <img src="{{aboutus.image}}" class="card-img-top" alt="...">
          <div class="card-body text-center">
            <h5 class="card-title mb-0">{{aboutus.titre}}</h5>
            <div class="card-text text-black-50">{{aboutus.job}}</div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <!-- /.row -->
  
  </div>
  <!-- /.container -->
{% endblock %}